In [25]:
import sys

from pandas import read_csv
from sklearn.preprocessing import LabelEncoder

data = read_csv("./spam_cleaned.csv")

label_encoder = LabelEncoder()
encoded = label_encoder.fit_transform(data['label'])
data['label'] = encoded

# Label encoder used to encode the label column to numerical values
print(data.head(5))

print(data.tail(5))




   label                                               text    len
0      0  point crazy available n great world la e buffe...  0.111
1      0                                         lar joke u  0.029
2      1  free entry win fa cup final text fa receive en...  0.155
3      0                                    u dun early u c  0.049
4      0                                      think go live  0.061
      label                                               text    len
5567      1  time try contact u win pound prize claim easy ...  0.160
5568      0                                b go esplanade home  0.037
5569      0                               pity mood suggestion  0.057
5570      0   guy bitch act like interested buy week give free  0.125
5571      0                                               true  0.026


In [26]:
from sklearn.feature_extraction.text import CountVectorizer


vectorizer = CountVectorizer(analyzer='word', stop_words='english', ngram_range=(1, 2))
data = data.dropna()
X = vectorizer.fit_transform(data['text'])
print(vectorizer.get_feature_names_out())
print(X.toarray())
y = data['label']

['aa' 'aa exhaust' 'abbey' ... 'zero saving' 'zoom' 'zoom cine']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [27]:
import numpy as np
# Top 5 and Bottom 5 of BOW

print(f"Feature Names: [{','.join(vectorizer.get_feature_names_out())}]")
print(f"Top 5: [{X.toarray()[:1]}]")
print(f"Bottom 5: {X.toarray()[-5:]}")

# The matrix is too large to be printed, but the top 5 and bottom 5 of the matrix are shown below.



Feature Names: [aa,aa exhaust,abbey,abbey happy,ability,ability listen,ability question,able,able buy,able class,able come,able deliver,able eat,able half,able join,able know,able late,able little,able meet,able morning,able pay,able raise,able reply,able shop,able sleep,able stool,able text,able value,able want,able yr,abnormally,abroad,abroad lonely,absence,absence gud,absolutely,absolutely love,abstract,abstract wake,abuse,abuser,abuser live,academic,academic department,academic secretary,accent,accent important,accept,accept brother,accept day,accept life,accept single,access,access adult,access day,access game,access number,access til,accessible,accessible week,accident,accident claim,accident divert,accidentally,accidentally bring,accidentally delete,accidentally leave,accommodation,accommodation global,accordingly,accordingly repeat,account,account ask,account balance,account bank,account cos,account credit,account delay,account dollar,account dry,account identification,account 

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the model
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

# Use Multinomial Naive Bayes as the model
model = MultinomialNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

# Got accuracy of 97.7% yay!
print(f"Accuracy: {accuracy}")

Accuracy: 0.9770431588613406
